### PR TITLE
Indicate the dependencies graph of each scanned library with issues #21

### PR DESCRIPTION
**Pull request by giacomuzzi**
Report example:

```
Scanning com.github.bumptech.glide:glide:3.8.0
 Graphs to this dependency:
 +---com.github.bumptech.glide:glide:3.8.0
 +---com.github.bumptech.glide:okhttp-integration:1.5.0
     +---com.github.bumptech.glide:glide:3.8.0
 +---com.gengqiquan:photoalbum:1.0.0
     +---com.github.bumptech.glide:glide:3.8.0
 Issues found:
 * com/bumptech/glide/Glide.class -> android/support/v4/app/FragmentActivity
 * com/bumptech/glide/Glide.class -> android/support/v4/app/Fragment
 * com/bumptech/glide/manager/RequestManagerRetriever.class -> android/support/v4/app/FragmentManager
 * com/bumptech/glide/manager/RequestManagerRetriever.class -> android/support/v4/app/FragmentActivity
 * com/bumptech/glide/manager/RequestManagerRetriever.class -> android/support/v4/app/Fragment
 * com/bumptech/glide/manager/RequestManagerRetriever.class -> android/support/v4/app/FragmentTransaction
 * com/bumptech/glide/manager/SupportRequestManagerFragment.class -> android/support/v4/app/Fragment
 * com/bumptech/glide/manager/SupportRequestManagerFragment.class -> android/support/v4/app/FragmentActivity
 * com/bumptech/glide/manager/SupportRequestManagerFragment.class -> android/support/v4/app/FragmentManager
 ```

### CODE REVIEW

**Comment by maxirosson** [comment]
There are conflicts to resolve before reviewing this PR.

**Comment by giacomuzzi** [comment]
I have just resolved all the conflicts

**Comment by maxirosson** [comment]
Is the first line after `Graphs to this dependency:` repeated?
` +---com.github.bumptech.glide:glide:3.8.0
`

**Comment by giacomuzzi** [comment]
That line is related to the first dependency declaration: 

```
	implementation("com.github.bumptech.glide:glide:3.8.0")
	implementation("com.github.bumptech.glide:okhttp-integration:1.5.0")
	implementation("com.gengqiquan:photoalbum:1.0.0")
```

**Comment by maxirosson** [comment]
ok. Makes sense

**Review by maxirosson — APPROVED** [review]

**Pull request merged**
